# Generated by Django 4.0.2 on 2022-02-22 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_school', models.CharField(max_length=75)),
                ('location', models.CharField(max_length=55)),
                ('start_year', models.DateField()),
                ('finish_year', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=25)),
                ('Description', models.TextField(max_length=350)),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_workplace', models.CharField(max_length=35)),
                ('location', models.CharField(max_length=35)),
                ('position', models.CharField(max_length=55)),
                ('start_time', models.DateField()),
                ('finish_time', models.DateField()),
            ],
        ),
    ]
